include(RunCMake)

set(RunCMake_TEST_NO_CLEAN 1)
set(RunCMake_TEST_BINARY_DIR ${RunCMake_BINARY_DIR})
MESSAGE(STATUS ${RunCMake_BINARY_DIR})
file(REMOVE_RECURSE ${RunCMake_BINARY_DIR})
run_cmake(Test)
file(READ ${RunCMake_BINARY_DIR}/ext ext)
run_cmake_command(Test-dep1 ${CMAKE_COMMAND} --build . --target CMakeFiles/dependent1.dir/test.c${ext})
run_cmake_command(Test ${CMAKE_COMMAND} --build . --target clean)
run_cmake_command(Test-dep2 ${CMAKE_COMMAND} --build . --target CMakeFiles/dependent2.dir/test.c${ext})
run_cmake_command(Test ${CMAKE_COMMAND} --build . --target clean)
run_cmake_command(Test-dep3 ${CMAKE_COMMAND} --build . --target CMakeFiles/dependent3.dir/test.c${ext})
run_cmake_command(Test ${CMAKE_COMMAND} --build . --target clean)
run_cmake_command(Test-dep4 ${CMAKE_COMMAND} --build . --target CMakeFiles/dependent4.dir/test.c${ext})
run_cmake_command(Test ${CMAKE_COMMAND} --build . --target clean)
